@startuml TD4.2.1


actor Enseignant
actor Etudiant
actor EnseignantResponsable

Enseignant <|-- EnseignantResponsable

Enseignant -- (Réserver des salles \n et du matériel)
Enseignant -- (Consulter planning des salles)
Etudiant -- (Consulter planning des salles)
Enseignant -- (Consulter recapitulatif horaires)
EnseignantResponsable -- (Editer recapitulatif horaire)



@enduml
