@startuml TD3.1.1
'--------------------------------
' Parametres pour le dessin
'--------------------------------
hide circle
hide empty members
hide empty methods
'--------------------------------

'usecase recenser as "Recenser les demandes de stage"

class Entreprise {
  nom
  adresse
  siegeSocial
}

class Etudiant {
  numINE
  nom
  prenom
  moyenneG
}

class Enseignant {
  nom
  prenom
  specialite
}

class Stage {
  lieu,
  dates
  entreprise
  nomTuteurEntreprise
  theme
}

class grTP {
  
}

class grTD {
  
}

class promo {
  
}

class Proposer {
  
}

class Participe {
  
}

class Etudie {
  
}

grTP --|> grTD
grTD --|> promo

Etudiant -- grTP
(Etudiant, grTP) . Etudie

Entreprise "1" -- "*" Stage
Etudiant "1" -- "0..1" Stage

(Entreprise, Stage) . Proposer



@enduml
