@startuml TD3.1.1
'--------------------------------
' Parametres pour le dessin
'--------------------------------
hide circle
hide empty members
hide empty methods
'--------------------------------

'usecase recenser as "Recenser les demandes de stage"

class Entreprise {
  nom
  adresse
  siegeSocial
}

class Etudiant {
  numINE
  nom
  prenom
  moyenneG
}

class Enseignant {
  nom
  prenom
  specialite
}

class Stage {
  lieu,
  dates
  entreprise
  nomTuteurEntreprise
  theme
}

class GrTP {
  
}

class GrTD {
  
}

class Promo {
  
}

class Proposer {
  
}

class Travailler {
  note
}

class Etudier {
  
}

class Superviser {
  
}

GrTP --|> GrTD
GrTD --|> Promo

Etudiant -- GrTP

Enseignant "*" -- "*" Etudiant

Entreprise "1" -- "*" Stage
Etudiant "1" -- "0..1" Stage

(Etudiant, GrTP) . Etudier
(Entreprise, Stage) . Proposer
(Etudiant, Stage) . Travailler
(Enseignant, Etudiant) . Superviser



@enduml
