@startuml TD5.2.1


participant client as ":Client"
participant caissier as ":Caissier"
participant caisse as ":Caisse"


client -> caisse: arriver

activate caissier

participant tapis as ":Tapis"

client -> tapis: deposerArticles

activate tapis

loop "Pour chaque article a"
  caissier -> tapis: prendreArticle
  caissier -> caisse: scan(client)
  activate caisse

  participant article as "a:article"

  par caisse --> article: getPrix()
  caisse --> article: getLibellé()

  else
  opt




@enduml
